# Generated by Django 3.0.9 on 2020-08-08 01:36

import crud_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_member_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=0, validators=[crud_app.models.check_age]),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, '5文字以上です！'), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみです！')]),
        ),
    ]
