# Generated by Django 3.0.9 on 2020-08-08 14:25

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=0, validators=[cms.models.check_age]),
        ),
    ]
