# Generated by Django 3.0.9 on 2020-08-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_member_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備考'),
        ),
    ]
