# Generated by Django 3.0.9 on 2020-08-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20200815_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='int_gender',
            field=models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (3, 'その他')], null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='性別'),
        ),
    ]
