# Generated by Django 3.1 on 2020-08-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
