# Generated by Django 3.1 on 2020-08-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_order_order_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ドリンク名')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.order')),
            ],
        ),
    ]
