# Generated by Django 3.1 on 2020-08-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_drink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='drink',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='member',
        ),
    ]
