# Generated by Django 3.1 on 2020-08-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20200818_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_num',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='ドリンク個数'),
        ),
    ]
