# Generated by Django 3.1 on 2020-08-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_drink_drink_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='コース名')),
                ('course_num', models.IntegerField(blank=True, default=1, null=True, verbose_name='コース個数')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.order')),
            ],
        ),
    ]
