# Generated by Django 3.1 on 2020-09-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
