# Generated by Django 3.1 on 2020-09-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='カテゴリ')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
