# Generated by Django 3.1 on 2020-09-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20200929_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuDesert',
        ),
        migrations.DeleteModel(
            name='MenuDrink',
        ),
        migrations.DeleteModel(
            name='MenuMain',
        ),
        migrations.DeleteModel(
            name='MenuZensai',
        ),
    ]
