# Generated by Django 3.1 on 2020-09-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20200930_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
    ]
